create database dbHospital




create table Paciente(
CODPAC INT IDENTITY (1,1) NOT NULL,
NOMPAC VARCHAR (120) NOT NULL,
APEPATRAC VARCHAR(120), 
FECNACPAC DATE NOT NULL,
SEXPAC CHAR (1) NOT NULL,
DNIPAC CHAR (8) NOT NULL,
TELEFPAC VARCHAR (9),
EMAILPAC VARCHAR (100),
DOMPAC VARCHAR (120) NOT NULL,
UBIGEOPAC CHAR (6) NOT NULL,
FECREGPAC DATETIME,
OBSERVPAC VARCHAR (250)
CONSTRAINT PK_CODPAC
PRIMARY KEY(CODPAC))
GO

SELECT * FROM Paciente


Create table Historia(
CODHIST INT IDENTITY(1,1) NOT NULL,
FECHIST DATETIME NOT NULL,
OBSHIST VARCHAR (1800)NOT NULL
CONSTRAINT PK_CODHIST
PRIMARY KEY(CODHIST))
GO

select * from historia


Create table Historia_Paciente(
CODHISST INT NOT NULL,
CODPAC INT,
CODMED INT
CONSTRAINT PK_CODHISST
PRIMARY KEY(CODHISST,CODPAC,CODMED))
GO

Create table Turno(
CODTUR INT IDENTITY (1,1) NOT NULL,
FECTUR DATETIME,
ESTTUR SMALLINT,
OBSTUR VARCHAR (500)
CONSTRAINT PK_CODTUR
PRIMARY KEY(CODTUR))
GO


CREATE TABLE TURNO_PACIENTE(
CODTUR INT NOT NULL,
CODPAC INT, 
CODMED INT 
CONSTRAINT PK_CODTUR
PRIMARY KEY(CODTUR))
GO


CREATE TABLE UBIGEO(
CODUB CHAR (6) NOT NULL,
DISTUB VARCHAR (60), 
PROVUB VARCHAR (60),
PAISUB  VARCHAR (60)  
CONSTRAINT PK_CODUB
PRIMARY KEY(CODUB))
GO

SELECT * FROM UBIGEO

CREATE TABLE  ESPECIALIDAD(
CODESP INT IDENTITY (1,1) NOT NULL,
NOMESP VARCHAR (80)NOT NULL,
OBSESP VARCHAR (100) 
CONSTRAINT PK_CODESP
PRIMARY KEY(CODESP))
GO

SELECT * FROM ESPECIALIDAD